In [3]:
import numpy as np
import pandas as pd
import datetime
import os
# ------- import ----------
from scrape_function import * 
from scrape_util import *

# combine df

In [5]:
home_movie = concat_df_from_dir('movies_at_home')

In [6]:
home_movie['platform'] = home_movie['date_list'].apply(lambda x:x.split()[0])
home_movie['movie_date'] = home_movie['date_list'].apply(lambda x:' '.join(x.split()[1:]))
home_movie['movie_date'] = pd.to_datetime(home_movie['movie_date'], format = '%b %d, %Y')
home_movie = home_movie[['title','critic_sentiment','critic_score','audience_setiment','audience_score','platform','movie_date']]
home_movie = home_movie

In [8]:
str_date = datetime(2020, 1, 1)
home_movie = home_movie[home_movie['movie_date'] > str_date]

In [12]:
home_movie

,title,critic_sentiment,critic_score,audience_setiment,audience_score,platform,movie_date
1,Jailbreak: Love on the Run,NaN,NaN,NaN,NaN,Streaming,2024-09-25
12,Inheritance,negative,24%,negative,26%,Streaming,2020-05-22
13,Spin the Bottle,NaN,NaN,NaN,NaN,Streaming,2024-10-04
16,The Abyss,NaN,NaN,negative,28%,Streaming,2024-02-16
23,Inside,positive,62%,negative,40%,Streaming,2023-04-04
...,...,...,...,...,...,...,...
20896,Code Name Banshee,negative,0%,positive,83%,Streaming,2022-07-01
20898,Crumb Catcher,positive,87%,positive,85%,Streaming,2024-08-20
20905,Force of Nature,negative,8%,negative,17%,Streaming,2020-06-30
20906,Four Hours at the Capitol,positive,89%,positive,62%,Streaming,2021-10-20
20909,Ginny Weds Sunny,negative,18%,positive,62%,Streaming,2020-10-09

In [14]:
all_title = home_movie['title'].tolist()

# get review data from combined title

In [21]:
first_iter = True
istr = 7000
istp = 8000
for title in all_title[istr:istp]:
    try:
        if first_iter:
            df_review = get_movie_reviews(title)
            first_iter = False
        else:
            df_review_ = get_movie_reviews(title)
            df_review = pd.concat([df_review,df_review_], ignore_index = True) 
    except Exception as e:
        print(f'Failed to get review from {title}:  {e}')

df_review.to_csv(f'review_at_home/get_review_data_red_{istr}_{istp}.csv', index = False)

NameError: name 'df_review' is not defined

In [25]:
len(all_title)

6227

In [11]:
df_review

,movie_title,movie_id,reviewer_name,review_date,review_score,review_sentiment,review_text,on_page
0,Pinball: The Man Who Saved the Game,3f42e95a-6b97-300e-b45f-103c710721de,John Serba,2023-08-14,Not found,POSITIVE,... So damn delightful â€“ itâ€™s surprisingly wit...,1.0
1,Pinball: The Man Who Saved the Game,3f42e95a-6b97-300e-b45f-103c710721de,Jason Delgado,2023-08-07,9/10,POSITIVE,Pinball: The Man Who Saved the Game exemplifie...,1.0
2,Pinball: The Man Who Saved the Game,3f42e95a-6b97-300e-b45f-103c710721de,Filipe Freitas,2023-04-11,4/5,POSITIVE,Pinball wonâ€™t be among your standard biopics b...,1.0
3,Pinball: The Man Who Saved the Game,3f42e95a-6b97-300e-b45f-103c710721de,Alex Maidy,2023-04-05,7/10,POSITIVE,With both Mike Faist and Crystal Reed exuding ...,1.0
4,Pinball: The Man Who Saved the Game,3f42e95a-6b97-300e-b45f-103c710721de,Kurt Loder,2023-03-31,Not found,POSITIVE,"The writer-directors, brothers Austin and Mere...",1.0
...,...,...,...,...,...,...,...,...
13369,Transfusion,e8474416-dd95-33cd-89a0-e7f8aba95fd5,Steve Biodrowski,2009-03-10,Not found,POSITIVE,It rocks with an incredible energy thanks to h...,1.0
13370,Transfusion,e8474416-dd95-33cd-89a0-e7f8aba95fd5,Scott Weinberg,2008-03-04,3.5/5,POSITIVE,"More than enough energy, mayhem and gore to ke...",1.0
13371,Transfusion,e8474416-dd95-33cd-89a0-e7f8aba95fd5,James O'Ehley,2008-02-26,Not found,NEGATIVE,Guaranteed to have you projectile vomiting all...,1.0
13372,Transfusion,e8474416-dd95-33cd-89a0-e7f8aba95fd5,Felix Vasquez Jr.,2008-02-23,3/4,POSITIVE,Ultimately it's hard to pronounce but fun to w...,1.0
13373,Transfusion,e8474416-dd95-33cd-89a0-e7f8aba95fd5,Steve,2007-06-22,2.5/5,NEGATIVE,The whole thing feels very thrown together wit...,1.0